version: "3.9"
services:
  trans_web:
    container_name: trans_web
    image: webtransbank:1.0
    build:
      context: $PWD/tiendatransbank-web
      dockerfile: $PWD/DockerfileReact
    ports:
      - 9999:3000
    depends_on:
      - trans_api
    networks:
      - tienda-net
  trans_api:
    container_name: trans_api
    image: resttransbank:1.0
    build:
      context: $PWD/tiendatransbank-rest
      dockerfile: $PWD/DockerfileSpring
    ports:
      - 9090:8080
    networks:
      - tienda-net
networks:
  tienda-net: 
    
