version: "3.9"
services:
  trans_web_dev:
    container_name: trans_web_dev
    image: webtransbank:1.0
    build:
      context: $PWD/tiendatransbank-web
      dockerfile: $PWD/DockerfileReact
    ports:
      - 9999:3000
    depends_on:
      - trans_api_dev
    networks:
      - tienda-net_dev
  trans_api_dev:
    container_name: trans_api_dev
    image: resttransbank:1.0
    build:
      context: $PWD/tiendatransbank-rest
      dockerfile: $PWD/DockerfileSpring
    ports:
      - 9091:8080
    networks:
      - tienda-net_dev
networks:
  tienda-net_dev: 
    
