version: '3.4'
services:
  bd_tienda:
    container_name: bd_tienda
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./../../BD_TIENDA:/data/db
    networks:
      - tienda-net
networks:
  tienda-net: